---
driver:
 name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 80, host: 1234}]
    - ["private_network", {ip: "33.33.33.10"}]

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[app_deploy]
    attributes:
