---
driver:
 name: vagrant

provisioner:
  name: chef_zero

driver_config:
  box: opscode-ubuntu-14.04
  box_url: http://files.vagrantup.com/precise32.box
  network:
    - ["forwarded_port", {guest: 80, host: 1234}]
    - ["private_network", {ip: "33.33.33.10"}]

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[app_deploy]
    attributes:
